name: Github Actions Demo
on: push
jobs:
  say-hello-world:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Hello World!'
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: List files
        run: ls {{ github.workspace }}
